DROP TABLE IF EXISTS `text`;
CREATE TABLE `text` (
  `id`   INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `text` TEXT    NOT NULL,
  `created_at` DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
